### ISSUE TITLE
Using collective.siteimprove in Plone 4

### ISSUE THREAD

**Issue by batlock666** [collective/collective.siteimprove#9]
I'm currently trying to modify collective.siteimprove so it can also be used in Plone 4. The Python/Plone changes are straightforward, but I can't get the JavaScript part working. Just adding siteimprove.js to postal_javascripts doesn't work, it needs require.js. But require.js is incompatible with portal_javascripts, it turns out. Can siteimprove.js be modified so it doesn't need require.js in Plone 4? What is this script supposed to do?

**Comment by witekdev** [comment]
Hi, sorry for the delayed response. We should probably setup notifications on this github repo. :man_facepalming: 

You should be able to modify it to work in Plone 4 I think. I'm not sure how involved the effort will be off-hand.

This is the reference from site improve that will explain things in detail:
 https://developer.siteimprove.com/siteimprove-cms-plugin-markdown/
https://developer.siteimprove.com/cms-plugin-integration-cookbook/
I'm sorry it's been too long since I worked on this and I don't have it all in my head at the moment.

There is also the https://github.com/collective/collective.siteimprove/blob/master/src/collective/siteimprove/browser/siteimprove-head.pt viewlet which calls methods defined in ``` siteimprove.js ``` that you will likely need to adapt as it also contains requireJS wrapped code.

Also keep in mind that Plone 4 sites have the ``` portal_url ``` variable available so this line from ``` siteimprove.js ```  :
``` this.url = $('body').data('portal-url'); ``` 
would instead probably be something like
```        this.url = portal_url; ```

**Comment by witekdev** [comment]
@batlock666 if you were to create a Plone 4 compatible version that is working, we could review it once its ready and make a release. Thanks!

**Comment by skleinfeldt** [comment]
@batlock666 I also want to apologize for not noticing your issue. I'm now watching the repo! Please ping us if we can answer further questions about a Plone 4 port.

**Comment by skleinfeldt** [comment]
PS We added you as a Contributor (see https://pypi.org/project/collective.siteimprove/)

**Comment by fiterbek** [comment]
I think this was fixed in https://github.com/collective/collective.siteimprove/pull/8 ?

**Comment by alecpm** [comment]
Unfortunately, the remaining issues are in the JS which is written specifically for sites that use requireJS (i.e Plone 5) and would have to be rewritten to support Plone 4 and the old JS registry. I'm not sure it's worth considering doing that given that Plone 4 is nearing its end of support life.

**Comment by fiterbek** [comment]
Agreed. I incorrectly assumed https://github.com/collective/collective.siteimprove/pull/8 fully fixed all issues, apologies.

**Comment by witekdev** [comment]
It is likely that with the merge of https://github.com/collective/collective.siteimprove/pull/13 this add-on should work in Plone 4 again, since we are no longer using the Plone5 resource registry. 
One can use the master branch directly now, and/or hopefully in the near future we will make the v1.0.7 release of the add-on.
